name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'salam, etdiyiniz problemləri bildirdiyiniz üçün təşəkkür edirik, tərtibatçı komandamız dərhal buna cavab verəcəkdir.'
        pr-message: 'salam, etdiyiniz çəkmə sorğusuna görə təşəkkür edirik, etdiyiniz çəkmə sorğusu vasitəsilə bu layihəni inkişaf etdirməkdə bizə qoşula bilsəniz çox şad olarıq.  tamam, bizim tərtibatçı komandamız buna tezliklə cavab verəcək.'
